Estacionamiento/Controllers/EstacionamientosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Estacionamiento.Models;

namespace Estacionamiento.Controllers
{
    public class EstacionamientosController : Controller
    {
        private EstacionamientosDB db = new EstacionamientosDB();

        // GET: Estacionamientos
        public ActionResult Index()
        {
            return View(db.Estacionamientos.ToList());
        }

        // GET: Estacionamientos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estacionamientos estacionamientos = db.Estacionamientos.Find(id);
            if (estacionamientos == null)
            {
                return HttpNotFound();
            }
            return View(estacionamientos);
        }

        // GET: Estacionamientos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Estacionamientos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EstacionamientosID,Fecha,Nivel,Placas")] Estacionamientos estacionamientos)
        {
            if (ModelState.IsValid)
            {
                db.Estacionamientos.Add(estacionamientos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(estacionamientos);
        }

        // GET: Estacionamientos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estacionamientos estacionamientos = db.Estacionamientos.Find(id);
            if (estacionamientos == null)
            {
                return HttpNotFound();
            }
            return View(estacionamientos);
        }

        // POST: Estacionamientos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EstacionamientosID,Fecha,Nivel,Placas")] Estacionamientos estacionamientos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estacionamientos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estacionamientos);
        }

        // GET: Estacionamientos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estacionamientos estacionamientos = db.Estacionamientos.Find(id);
            if (estacionamientos == null)
            {
                return HttpNotFound();
            }
            return View(estacionamientos);
        }

        // POST: Estacionamientos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estacionamientos estacionamientos = db.Estacionamientos.Find(id);
            db.Estacionamientos.Remove(estacionamientos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Estacionamiento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title -Estacionamiento</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
	


</head>
<body>
	
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
                @Html.ActionLink("Anbrera", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Inicio", "Index", "Home")</li>
					<li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
					<li>@Html.ActionLink("Acerca de", "About", "Home")</li>
					<li>@Html.ActionLink("Estacionamiento", "Est", "Home")</li>
					
					<li>@Html.ActionLink("Ingreso", "Index", "Estacionamientos")</li>
					

				</ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - Tecnologico de Estudio Superiores Huixquilucan</p>
			

		</footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>